version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vectora-backend-lambda"
region = "ap-south-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "vectora-backend-lambda"
disable_rollback = false
image_repositories = []
